# Generated by Django 5.0.10 on 2024-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='selected_seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
