# Generated by Django 5.0.10 on 2024-12-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_customer_seat_number_customer_selected_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='available_seats',
        ),
    ]
