# Generated by Django 5.0.10 on 2024-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_flight_available_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSeats',
            fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('flight_id', models.IntegerField()),
            ('selected_seat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlightsBackup',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('flight_id', models.IntegerField()),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('backup_time', models.DateTimeField()),
            ],
        ),
    ]
