# Generated by Django 5.0.10 on 2024-12-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_customerseats_flightsbackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerseats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='flightsbackup',
            options={'managed': False},
        ),
    ]
