# Generated by Django 5.0.10 on 2024-12-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_customerseats_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerseats',
            table='CustomerSeats',
        ),
    ]
