# Generated by Django 5.0.10 on 2024-12-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_customerseats_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flightsbackup',
            table='FlightsBackup',
        ),
    ]
