# Generated by Django 5.0.10 on 2025-01-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0007_alter_flightsbackup_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_id", models.IntegerField()),
                ("departure_city", models.CharField(max_length=100)),
                ("arrival_city", models.CharField(max_length=100)),
                ("departure_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "selected_seat",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "vw_FlightDetails",
                "managed": False,
            },
        ),
    ]
